### ISSUE TITLE
Pandoc error when trying to include rbokeh plot in rmarkdown document

### ISSUE THREAD

**Issue by seandavi** [bokeh/rbokeh#40] opened 2015-02-24 23:11 UTC
I have a small block in an Rmarkdown document in which I am trying to include an rbokeh plot.  

```r
'''{r}
library(rbokeh)
p <- figure() %>%
  ly_points(Sepal.Length, Sepal.Width, data = iris,
    color = Species, glyph = Species,
    hover = list(Sepal.Length, Sepal.Width))
p
'''
```

I get this error when I try knitting the document.  On the file system, this file does not exist.  In fact, even the images folder does not exist.

```r
pandoc: Could not find data file /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rbokeh/htmlwidgets/lib/bokehjs/images/ui-bg_flat_75_ffffff_40x100.png
Error: pandoc document conversion failed with error 97
Execution halted
```

And sessionInfo():

```r
> sessionInfo()
R Under development (unstable) (2014-10-24 r66864)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] rbokeh_0.2           BiocInstaller_1.17.5

loaded via a namespace (and not attached):
 [1] devtools_1.6.1    digest_0.6.4      evaluate_0.5.5    formatR_1.0
 [5] grid_3.2.0        hexbin_1.27.0     htmltools_0.2.6   htmlwidgets_0.3.2
 [9] httr_0.5          knitr_1.8         lattice_0.20-29   magrittr_1.5
[13] maps_2.3-9        RCurl_1.95-4.3    RJSONIO_1.3-0     stringr_0.6.2
[17] tcltk_3.2.0       tools_3.2.0
```

Any suggestions?

**Comment by hafen** [comment] 2015-02-24 23:18
Interesting.  Haven't seen this before.  Could you provide the command you are using to knit the document?

**Comment by seandavi** [comment] 2015-02-24 23:23
Thanks, @hafen, for the quick response.  Here are some more details.  

```r
> rmarkdown::render('abc.Rmd')


processing file: abc.Rmd
  |................                                                 |  25%
  ordinary text without R code

  |................................                                 |  50%
label: unnamed-chunk-1
  |.................................................                |  75%
  ordinary text without R code

  |.................................................................| 100%
label: unnamed-chunk-2

output file: abc.knit.md

/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc abc.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output abc.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rmarkdown/rmd/h/default.html --variable 'theme:bootstrap' --include-in-header /var/folders/21/b_rp6qyj1_b1j5cp8qby0tnr0000gn/T//RtmpwSJoQs/rmarkdown-str5049669973b3.html --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --no-highlight --variable highlightjs=/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rmarkdown/rmd/h/highlight 
pandoc: Could not find data file /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rbokeh/htmlwidgets/lib/bokehjs/images/ui-bg_flat_75_ffffff_40x100.png
Error: pandoc document conversion failed with error 97
```

**Comment by timelyportfolio** [comment] 2015-02-25 00:04
I ran into the problem today also.  I think I know a fix and will try to push tonight.

**Comment by hafen** [comment] 2015-02-25 03:41
Thanks for the detail.  I see what the issue is now.  At the moment, to make it work, you need to have the following in your front matter:

    ---
    output:
      html_document:
        self_contained: no
    ---

At the least, this should be documented.  But I suppose we should make self_contained possible as well.  @timelyportfolio, is this what your fix is addressing?  Do you have a feel for what is needed?  I'd hate to bulk up the size of the package with too many files.  Perhaps @ramnathv has some insight from his initial work with rbokeh.

**Comment by timelyportfolio** [comment] 2015-02-25 03:54
Yes this is the issue.  I just want to understand how many files.

**Comment by hafen** [comment] 2015-02-25 03:59
Maybe it's just the images (see [here](https://github.com/ramnathv/rbokeh/tree/master/inst/htmlwidgets/bokeh))

**Comment by timelyportfolio** [comment] 2015-02-25 04:06
I think it is just the icons. Was not able to look tonight.  Can fix first thing in the morning.

**Comment by hafen** [comment] 2015-02-25 05:26
Sounds great.  I looked into it some more.  I just kept finding files and moving them to where it was expecting them - see the branch [here](https://github.com/hafen/rbokeh/tree/feature-self-contained).  But even then I get this error:

```
pandoc: Could not fetch /Users/hafen/Library/R/3.1/library/rbokeh/htmlwidgets/lib/bokehjs/data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale
/Users/hafen/Library/R/3.1/library/rbokeh/htmlwidgets/lib/bokehjs/data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
```

**Comment by seandavi** [comment] 2015-02-25 11:48
Adding this YAML front matter works to get a plot.  Thanks to you both for looking into it.

```
---
output:
  html_document:
    self_contained: no
---
```

I'm curious what it is going to take to get things back to `self_contained: yes`.

**Comment by timelyportfolio** [comment] 2015-02-25 15:20
@hafen, that is very strange that pandoc / rmarkdown is trying to base encode the svg namespace.  I'll look around.  We might be able to remove, but don't think this is the best option.

**Comment by timelyportfolio** [comment] 2015-02-25 15:32
Ok, I think I got it using help from http://stackoverflow.com/questions/10768451/inline-svg-in-css.  We can base64encode this ourselves.  Will push a branch shortly.

**Comment by timelyportfolio** [comment] 2015-02-25 15:59
Ok, with the pull, I think it is all set.

**Comment by hafen** [comment] 2015-02-26 07:16
Thans @timelyportfolio.  For some reason I can't see the exactly what was changed - probably because it's a one-line minified css.  It looks like this is something we would need to modify every time we update BokehJS?  If so, maybe we should see if they can make the change upstream in BokehJS?

**Comment by timelyportfolio** [comment] 2015-02-26 14:55
Oh, I should have thought about that.  I'll separate the commits by new line where I made the change and I think it will then show up.

@bryevdv , thoughts on base64 encoding the svg filter in bokeh.css [lines](https://github.com/bokeh/bokeh/blob/6bff365eb13e4a1288fa273700d40c3420137b9a/bokehjs/src/less/continuum.less#L85-L94)?

**Comment by timelyportfolio** [comment] 2015-02-26 15:34
well, it still does not show up cleanly, but the effect is on this [line](https://github.com/bokeh/rbokeh/blob/19ac668afe86bd0942e932bea8ae62dee72f11da/inst/htmlwidgets/lib/bokehjs/bokeh.min.css#L159)

we go from 

```
.bk-logo.grey{filter:url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale");filter:gray;-webkit-filter:grayscale(100%)}
```

to

```
.bk-logo.grey{filter:url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPjxmaWx0ZXIgaWQ9J2dyYXlzY2FsZSc+PGZlQ29sb3JNYXRyaXggdHlwZT0nbWF0cml4JyB2YWx1ZXM9JzAuMzMzMyAwLjMzMzMgMC4zMzMzIDAgMCAwLjMzMzMgMC4zMzMzIDAuMzMzMyAwIDAgMC4zMzMzIDAuMzMzMyAwLjMzMzMgMCAwIDAgMCAwIDEgMCcvPjwvZmlsdGVyPjwvc3ZnPg==");filter:gray;-webkit-filter:grayscale(100%)}
```

There are a couple ways to do it, but in R, we can 

```R
base64enc::base64encode(charToRaw("<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>"))
```

and then change `utf8` to `base64` and replace the svg tag with the base64 value.

**Comment by ramnathv** [comment] 2015-02-26 16:15
You may also want to submit this issue to the `pandoc` github repo since this is something `pandoc` should be able to handle.

**Comment by hafen** [comment] 2015-07-09 04:05
While hopefully this gets addressed more permanently in Bokeh or Pandoc, I'm closing since we have manually fixed it in both master and dev, and I just added a test in dev (https://github.com/bokeh/rbokeh/pull/93) that will ensure when we add new Bokeh css updates we don't sneak this problem back in.

**Closed by hafen** 2015-07-09 04:05 UTC
